//
// Created by vrwanda on 3/5/20.
//



#ifndef DBCRUDGEN_CPP_CPPMYSQLPROJECTCODEGEN_H
#define DBCRUDGEN_CPP_CPPMYSQLPROJECTCODEGEN_H

class CppMYSQLProjectCodeGen {

};

#endif //DBCRUDGEN_CPP_CPPMYSQLPROJECTCODEGEN_H