//
// Created by vrwanda on 3/5/20.
//


#ifndef DBCRUDGEN_CPP_CPPMYSQLCONNECTORTEMPLATE_H
#define DBCRUDGEN_CPP_CPPMYSQLCONNECTORTEMPLATE_H

class CppMYSQLConnectorTemplate {

};

#endif //DBCRUDGEN_CPP_CPPMYSQLCONNECTORTEMPLATE_H