//
// Created by vrwanda on 3/5/20.
//


#ifndef DBCRUDGEN_CPP_CPPSQLITECONNECTORTEMPLATE_H
#define DBCRUDGEN_CPP_CPPSQLITECONNECTORTEMPLATE_H

class CppSQLiteConnectorTemplate {

};

#endif //DBCRUDGEN_CPP_CPPSQLITECONNECTORTEMPLATE_H