//
// Created by vrwanda on 3/5/20.
//


#ifndef DBCRUDGEN_CPP_JAVAMYSQLCONNECTORTEMPLATE_H
#define DBCRUDGEN_CPP_JAVAMYSQLCONNECTORTEMPLATE_H

class JavaMYSQLConnectorTemplate {

};

#endif //DBCRUDGEN_CPP_JAVAMYSQLCONNECTORTEMPLATE_H