//
// Created by vrwanda on 3/5/20.
//


#ifndef DBCRUDGEN_CPP_JAVAORACLEPROJECTCODEGEN_H
#define DBCRUDGEN_CPP_JAVAORACLEPROJECTCODEGEN_H

class JavaOracleProjectCodeGen {

};


#endif //DBCRUDGEN_CPP_JAVAORACLEPROJECTCODEGEN_H