//
// Created by vrwanda on 3/5/20.
//


#ifndef DBCRUDGEN_CPP_JAVAMYSQLPROJECTCODEGEN_H
#define DBCRUDGEN_CPP_JAVAMYSQLPROJECTCODEGEN_H

class JavaMYSQLProjectCodeGen {

};


#endif //DBCRUDGEN_CPP_JAVAMYSQLPROJECTCODEGEN_H