//
// Created by vrwanda on 3/5/20.
//

#ifndef DBCRUDGEN_CPP_SWIFTMYSQLPROJECTCREATOR_H
#define DBCRUDGEN_CPP_SWIFTMYSQLPROJECTCREATOR_H

class SwiftMYSQLProjectCreator {

};


#endif //DBCRUDGEN_CPP_SWIFTMYSQLPROJECTCREATOR_H
