//
// Created by vrwanda on 3/5/20.
//

#ifndef DBCRUDGEN_CPP_SWIFTORACLEPROJECTCREATOR_H
#define DBCRUDGEN_CPP_SWIFTORACLEPROJECTCREATOR_H

class SwiftOracleProjectCreator {

};

#endif //DBCRUDGEN_CPP_SWIFTORACLEPROJECTCREATOR_H
