//
// Created by vrwanda on 3/5/20.
//


#ifndef DBCRUDGEN_CPP_ANDROIDCONTENTPROVIDERTEMPLATE_H
#define DBCRUDGEN_CPP_ANDROIDCONTENTPROVIDERTEMPLATE_H

class AndroidContentProviderTemplate {

};

#endif //DBCRUDGEN_CPP_ANDROIDCONTENTPROVIDERTEMPLATE_H