//
// Created by vrwanda on 3/6/20.
//

#ifndef DBCRUDGEN_CPP_COLLATIONCHARACTERSETAPPLICABILITY_H
#define DBCRUDGEN_CPP_COLLATIONCHARACTERSETAPPLICABILITY_H


class CollationCharacterSetApplicability {

};


#endif //DBCRUDGEN_CPP_COLLATIONCHARACTERSETAPPLICABILITY_H
