//
// Created by vrwanda on 3/6/20.
//

#ifndef DBCRUDGEN_CPP_INNODBFTDEFAULTSTOPWORD_H
#define DBCRUDGEN_CPP_INNODBFTDEFAULTSTOPWORD_H


class InnoDbFtDefaultStopWord {

};


#endif //DBCRUDGEN_CPP_INNODBFTDEFAULTSTOPWORD_H
