//
// Created by vrwanda on 3/6/20.
//

#ifndef DBCRUDGEN_CPP_INNODBBUFFERPOOLSTATS_H
#define DBCRUDGEN_CPP_INNODBBUFFERPOOLSTATS_H


class InnoDbBufferPoolStats {

};


#endif //DBCRUDGEN_CPP_INNODBBUFFERPOOLSTATS_H
