//
// Created by vrwanda on 3/5/20.
//

#ifndef DBCRUDGEN_CPP_ANDROIDPROJECTCODEGEN_H
#define DBCRUDGEN_CPP_ANDROIDPROJECTCODEGEN_H

class AndroidProjectCodeGen {

};

#endif //DBCRUDGEN_CPP_ANDROIDPROJECTCODEGEN_H